modLoader="javafml" #mandatory
loaderVersion="[4,)"
license="MIT"
[[mods]] #mandatory
modId="afc" #mandatory
version="2.1.2-1.21" #mandatory
displayName="ArborFirmaCraft" #mandatory
logoFile="examplemod.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Therighthon" #optional
description='''
An addon for TerraFirmaCraft centered around new species of trees.
'''
[[mixins]]
config="afc.mixins.json"
[[dependencies.afc]]
    modId="tfc"
    mandatory=true
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.afc]]
    modId="neoforge"
    mandatory=true
    versionRange="[21.0.143,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.afc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1,1.21.2)"
    ordering="AFTER"
    side="BOTH"
